name: ECGI_FEM
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - pytorch-cuda=11.8
  - numpy
  - scipy
  - pandas
  - matplotlib
  - tqdm
  - tensorboard
  - scikit-sparse
  - vtk
  - ipykernel  
  - pip
  - pip:
      - scikit-fem
      - meshio
      - pyvista
      - cupy-cuda11x
      - torchdeq